keywords = ["LAZYPAY","CHICKEN","SWIGGYINSTAMART","VERIFY","RESTAURANT","BOOKMYSHOW","KFC", "VESTED",
            "POLICE","JIOFIBER", "DMARTINDIA", "TEA", "AMAZON", "DOSA", "RETAIL",
            "METRO", "INDIANCLEARINGCORPOR", "FOOD", "EAW", "GROWW", "NEXTBILLION", "ZERODHA", "IDLY", 
            "SIMPL", "SWIGGY", "IRCTC", "REDBUS", "NWD", "PAYMENTTOROPPENTRA", "RATNADEEP", "YATRA", 
            "UPIRET", "SOUTH", "RAZORPAY", "SAFEGOLD", "JIO", "IIT", "SALARY", "NPS", "ACH", "CLEARING",
            "CFSIMPL", "NEFT", "ICCLMF", "PVRCINEMAS", "STORES", "URBANCOMPANY", "POS", "MF", "IMPS",
            "PG", "DECATHLON", "REDBUSIN", "INTEREST"]